# Generated by Django 3.2.10 on 2022-05-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_auto_20220523_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='vertical_image',
            field=models.ImageField(default=1, upload_to='banner/', verbose_name='Banner telefon üçin'),
            preserve_default=False,
        ),
    ]
