# Generated by Django 3.2.10 on 2022-05-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_alter_banner_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon nomer'),
        ),
    ]
