# Generated by Django 3.2.10 on 2022-05-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_alter_companyinfo_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutproduct',
            options={'verbose_name': 'Haryt barada', 'verbose_name_plural': '4. Harytlar barada'},
        ),
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'Kompaniýa barada', 'verbose_name_plural': '3. Kompaniýa barada'},
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Banner', 'verbose_name_plural': '2. Bannerlar'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriýa', 'verbose_name_plural': '5. Kategoriýalar'},
        ),
        migrations.AlterModelOptions(
            name='certification',
            options={'verbose_name': 'Sertifikat', 'verbose_name_plural': '9. Sertifikatlar'},
        ),
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'verbose_name': 'Kompaniýanyň maglymaty', 'verbose_name_plural': '1. Kompaniýanyň maglymatlary'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Kontakt', 'verbose_name_plural': '8. Kontaktlar'},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Gelen Hat', 'verbose_name_plural': '10. Gelen hatlar'},
        ),
        migrations.AlterModelOptions(
            name='footerdesc',
            options={'verbose_name': 'Aşakdaky Beýan', 'verbose_name_plural': '7. Aşakdaky Beýanlar'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Haryt', 'verbose_name_plural': '6. Harytlar'},
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='logo_mini',
            field=models.ImageField(upload_to='logo/', verbose_name='Logo Kici'),
        ),
    ]
