# Generated by Django 3.2.10 on 2022-05-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_auto_20220528_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerdesc',
            name='desc',
            field=models.TextField(verbose_name='Beýany'),
        ),
    ]
