# Generated by Django 3.2.11 on 2022-06-17 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_alter_footerdesc_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='image_fo',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='image_three',
        ),
    ]
