# Generated by Django 3.2.10 on 2022-05-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RuApp', '0003_alter_banner_vertical_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='image_fo',
            field=models.ImageField(upload_to='kompsurat/', verbose_name='Четвертое фото'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image_one',
            field=models.ImageField(upload_to='kompsurat/', verbose_name='Первое фото'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image_second',
            field=models.ImageField(upload_to='kompsurat/', verbose_name='Второе фото'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image_three',
            field=models.ImageField(upload_to='kompsurat/', verbose_name='Третее фото'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='active',
            field=models.CharField(blank=True, choices=[('active', 'active')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='footerdesc',
            name='image',
            field=models.ImageField(upload_to='footerdesc/', verbose_name='Изоброжение'),
        ),
    ]
