# Generated by Django 3.2.10 on 2022-05-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RuApp', '0004_auto_20220523_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='image_fo',
            field=models.ImageField(upload_to='komp_surat/', verbose_name='Четвертое фото'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image_one',
            field=models.ImageField(upload_to='komp_surat/', verbose_name='Первое фото'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image_second',
            field=models.ImageField(upload_to='komp_surat/', verbose_name='Второе фото'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image_three',
            field=models.ImageField(upload_to='komp_surat/', verbose_name='Третее фото'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='footerdesc',
            name='image',
            field=models.ImageField(upload_to='footer_desc/', verbose_name='Изоброжение'),
        ),
    ]
